name:                crypto-depth-db
version:             0.1.0.0
github:              "runeksvendsen/crypto-depth-db"
license:             BSD3
author:              "Rune K. Svendsen"
maintainer:          "runesvend@gmail.com"
copyright:           "CC0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/runeksvendsen/crypto-depth-db#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- crypto-depth
- crypto-venues
- orderbook
- beam-core
- beam-migrate
- beam-postgres
- postgresql-simple
- time
- unordered-containers
- safe-money
- tagged
- text
- vector
- aeson
- bytestring
- scientific

default-extensions:
- DeriveGeneric
- GADTs
- OverloadedStrings
- FlexibleContexts
- FlexibleInstances
- TypeFamilies
- TypeApplications
- DataKinds
- StandaloneDeriving
- TypeSynonymInstances
- MultiParamTypeClasses
- RecordWildCards
- ScopedTypeVariables

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  crypto-depth-db-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-depth-db
    - http-client
    - monad-parallel
    - http-client-tls
    - logging

tests:
  crypto-depth-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-depth-db
